# Generated by Django 3.0.7 on 2021-02-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='next_check',
            field=models.CharField(default='2137', max_length=16),
        ),
        migrations.AlterField(
            model_name='monitorobject',
            name='url',
            field=models.URLField(default='2137'),
            preserve_default=False,
        ),
    ]
