# Generated by Django 3.0.7 on 2021-02-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20210205_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorobject',
            name='next_check',
            field=models.CharField(default='2137', max_length=32),
        ),
    ]
