# Generated by Django 3.0.7 on 2021-02-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.BooleanField(max_length=4),
        ),
    ]
